import Vue from 'vue';
import __vue_component__ from './lib/S-Tree/index.mjs';
import __vue_component__$1 from './lib/S-Form/index.mjs';
import __vue_component__$2 from './lib/S-Ellipsis/index.mjs';
import __vue_component__$3 from './lib/S-IconSelect/index.mjs';
import __vue_component__$4 from './lib/S-EditCell/Input.mjs';
import __vue_component__$5 from './lib/S-EditCell/Select.mjs';
import __vue_component__$6 from './lib/S-EditCell/Textarea.mjs';
import __vue_component__$7 from './lib/S-EditCell/DatePicker.mjs';
import __vue_component__$8 from './lib/S-EditCell/TreeSelect.mjs';
import STableFilter from './lib/S-Table/filter.mjs';
import STable from './lib/S-Table/index.mjs';
import 'ant-design-vue/es/pagination/style';
import _Pagination from 'ant-design-vue/es/pagination';
import 'ant-design-vue/es/time-picker/style';
import TimePicker from 'ant-design-vue/es/time-picker';
import 'ant-design-vue/es/date-picker/style';
import DatePicker from 'ant-design-vue/es/date-picker';
import 'ant-design-vue/es/tooltip/style';
import Tooltip from 'ant-design-vue/es/tooltip';
import 'ant-design-vue/es/table/style';
import _Table from 'ant-design-vue/es/table';
import 'ant-design-vue/es/tree/style';
import _Tree from 'ant-design-vue/es/tree';
import 'ant-design-vue/es/spin/style';
import _Spin from 'ant-design-vue/es/spin';
import 'ant-design-vue/es/icon/style';
import _Icon from 'ant-design-vue/es/icon';
import 'ant-design-vue/es/col/style';
import _Col from 'ant-design-vue/es/col';
import 'ant-design-vue/es/row/style';
import _Row from 'ant-design-vue/es/row';
import 'ant-design-vue/es/form/style';
import _Form from 'ant-design-vue/es/form';
import 'ant-design-vue/es/select/style';
import ASelect from 'ant-design-vue/es/select';
import 'ant-design-vue/es/radio/style';
import ARadio from 'ant-design-vue/es/radio';
import 'ant-design-vue/es/switch/style';
import ASwitch from 'ant-design-vue/es/switch';
import 'ant-design-vue/es/button/style';
import _Button from 'ant-design-vue/es/button';
import 'ant-design-vue/es/checkbox/style';
import ACheckbox from 'ant-design-vue/es/checkbox';
import 'ant-design-vue/es/input-number/style';
import AInputNumber from 'ant-design-vue/es/input-number';
import 'ant-design-vue/es/auto-complete/style';
import AutoComplete from 'ant-design-vue/es/auto-complete';
import 'ant-design-vue/es/tree-select/style';
import ATreeSelect from 'ant-design-vue/es/tree-select';
import 'ant-design-vue/es/cascader/style';
import ACascader from 'ant-design-vue/es/cascader';
import 'ant-design-vue/es/input/style';
import AInput from 'ant-design-vue/es/input';
import 'ant-design-vue/es/rate/style';
import ARate from 'ant-design-vue/es/rate';

Vue.use(ARate);
Vue.use(AInput);
Vue.use(ACascader);
Vue.use(ATreeSelect);
Vue.use(AutoComplete);
Vue.use(AInputNumber);
Vue.use(ACheckbox);
Vue.use(_Button);
Vue.use(ASwitch);
Vue.use(ARadio);
Vue.use(ASelect);
Vue.use(_Form);
Vue.use(_Row);
Vue.use(_Col);
Vue.use(_Icon);
Vue.use(_Spin);
Vue.use(_Tree);
Vue.use(_Table);
Vue.use(Tooltip);
Vue.use(DatePicker);
Vue.use(TimePicker);
Vue.use(_Pagination);

Vue.component('STree', __vue_component__);
Vue.component('SForm', __vue_component__$1);
Vue.component('SEllipsis', __vue_component__$2);
Vue.component('SIconSelect', __vue_component__$3);
Vue.component('SEditCellInput', __vue_component__$4);
Vue.component('SEditCellSelect', __vue_component__$5);
Vue.component('SEditCellTextarea', __vue_component__$6);
Vue.component('SEditCellDatePicker', __vue_component__$7);
Vue.component('SEditCellTreeSelect', __vue_component__$8);
Vue.component('STableFilter', STableFilter);
Vue.component('STable', STable);
