'use strict';

var Vue = require('vue');
var index = require('./lib/S-Tree/index.cjs');
var index$1 = require('./lib/S-Form/index.cjs');
var index$2 = require('./lib/S-Ellipsis/index.cjs');
var index$3 = require('./lib/S-IconSelect/index.cjs');
var Input = require('./lib/S-EditCell/Input.cjs');
var Select = require('./lib/S-EditCell/Select.cjs');
var Textarea = require('./lib/S-EditCell/Textarea.cjs');
var DatePicker$1 = require('./lib/S-EditCell/DatePicker.cjs');
var TreeSelect = require('./lib/S-EditCell/TreeSelect.cjs');
var filter = require('./lib/S-Table/filter.cjs');
var index$4 = require('./lib/S-Table/index.cjs');
require('ant-design-vue/es/pagination/style');
var _Pagination = require('ant-design-vue/es/pagination');
require('ant-design-vue/es/time-picker/style');
var TimePicker = require('ant-design-vue/es/time-picker');
require('ant-design-vue/es/date-picker/style');
var DatePicker = require('ant-design-vue/es/date-picker');
require('ant-design-vue/es/tooltip/style');
var Tooltip = require('ant-design-vue/es/tooltip');
require('ant-design-vue/es/table/style');
var _Table = require('ant-design-vue/es/table');
require('ant-design-vue/es/tree/style');
var _Tree = require('ant-design-vue/es/tree');
require('ant-design-vue/es/spin/style');
var _Spin = require('ant-design-vue/es/spin');
require('ant-design-vue/es/icon/style');
var _Icon = require('ant-design-vue/es/icon');
require('ant-design-vue/es/col/style');
var _Col = require('ant-design-vue/es/col');
require('ant-design-vue/es/row/style');
var _Row = require('ant-design-vue/es/row');
require('ant-design-vue/es/form/style');
var _Form = require('ant-design-vue/es/form');
require('ant-design-vue/es/select/style');
var ASelect = require('ant-design-vue/es/select');
require('ant-design-vue/es/radio/style');
var ARadio = require('ant-design-vue/es/radio');
require('ant-design-vue/es/switch/style');
var ASwitch = require('ant-design-vue/es/switch');
require('ant-design-vue/es/button/style');
var _Button = require('ant-design-vue/es/button');
require('ant-design-vue/es/checkbox/style');
var ACheckbox = require('ant-design-vue/es/checkbox');
require('ant-design-vue/es/input-number/style');
var AInputNumber = require('ant-design-vue/es/input-number');
require('ant-design-vue/es/auto-complete/style');
var AutoComplete = require('ant-design-vue/es/auto-complete');
require('ant-design-vue/es/tree-select/style');
var ATreeSelect = require('ant-design-vue/es/tree-select');
require('ant-design-vue/es/cascader/style');
var ACascader = require('ant-design-vue/es/cascader');
require('ant-design-vue/es/input/style');
var AInput = require('ant-design-vue/es/input');
require('ant-design-vue/es/rate/style');
var ARate = require('ant-design-vue/es/rate');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var Vue__default = /*#__PURE__*/_interopDefaultLegacy(Vue);
var _Pagination__default = /*#__PURE__*/_interopDefaultLegacy(_Pagination);
var TimePicker__default = /*#__PURE__*/_interopDefaultLegacy(TimePicker);
var DatePicker__default = /*#__PURE__*/_interopDefaultLegacy(DatePicker);
var Tooltip__default = /*#__PURE__*/_interopDefaultLegacy(Tooltip);
var _Table__default = /*#__PURE__*/_interopDefaultLegacy(_Table);
var _Tree__default = /*#__PURE__*/_interopDefaultLegacy(_Tree);
var _Spin__default = /*#__PURE__*/_interopDefaultLegacy(_Spin);
var _Icon__default = /*#__PURE__*/_interopDefaultLegacy(_Icon);
var _Col__default = /*#__PURE__*/_interopDefaultLegacy(_Col);
var _Row__default = /*#__PURE__*/_interopDefaultLegacy(_Row);
var _Form__default = /*#__PURE__*/_interopDefaultLegacy(_Form);
var ASelect__default = /*#__PURE__*/_interopDefaultLegacy(ASelect);
var ARadio__default = /*#__PURE__*/_interopDefaultLegacy(ARadio);
var ASwitch__default = /*#__PURE__*/_interopDefaultLegacy(ASwitch);
var _Button__default = /*#__PURE__*/_interopDefaultLegacy(_Button);
var ACheckbox__default = /*#__PURE__*/_interopDefaultLegacy(ACheckbox);
var AInputNumber__default = /*#__PURE__*/_interopDefaultLegacy(AInputNumber);
var AutoComplete__default = /*#__PURE__*/_interopDefaultLegacy(AutoComplete);
var ATreeSelect__default = /*#__PURE__*/_interopDefaultLegacy(ATreeSelect);
var ACascader__default = /*#__PURE__*/_interopDefaultLegacy(ACascader);
var AInput__default = /*#__PURE__*/_interopDefaultLegacy(AInput);
var ARate__default = /*#__PURE__*/_interopDefaultLegacy(ARate);

Vue__default["default"].use(ARate__default["default"]);
Vue__default["default"].use(AInput__default["default"]);
Vue__default["default"].use(ACascader__default["default"]);
Vue__default["default"].use(ATreeSelect__default["default"]);
Vue__default["default"].use(AutoComplete__default["default"]);
Vue__default["default"].use(AInputNumber__default["default"]);
Vue__default["default"].use(ACheckbox__default["default"]);
Vue__default["default"].use(_Button__default["default"]);
Vue__default["default"].use(ASwitch__default["default"]);
Vue__default["default"].use(ARadio__default["default"]);
Vue__default["default"].use(ASelect__default["default"]);
Vue__default["default"].use(_Form__default["default"]);
Vue__default["default"].use(_Row__default["default"]);
Vue__default["default"].use(_Col__default["default"]);
Vue__default["default"].use(_Icon__default["default"]);
Vue__default["default"].use(_Spin__default["default"]);
Vue__default["default"].use(_Tree__default["default"]);
Vue__default["default"].use(_Table__default["default"]);
Vue__default["default"].use(Tooltip__default["default"]);
Vue__default["default"].use(DatePicker__default["default"]);
Vue__default["default"].use(TimePicker__default["default"]);
Vue__default["default"].use(_Pagination__default["default"]);

Vue__default["default"].component('STree', index["default"]);
Vue__default["default"].component('SForm', index$1["default"]);
Vue__default["default"].component('SEllipsis', index$2["default"]);
Vue__default["default"].component('SIconSelect', index$3["default"]);
Vue__default["default"].component('SEditCellInput', Input["default"]);
Vue__default["default"].component('SEditCellSelect', Select["default"]);
Vue__default["default"].component('SEditCellTextarea', Textarea["default"]);
Vue__default["default"].component('SEditCellDatePicker', DatePicker$1["default"]);
Vue__default["default"].component('SEditCellTreeSelect', TreeSelect["default"]);
Vue__default["default"].component('STableFilter', filter["default"]);
Vue__default["default"].component('STable', index$4["default"]);
